package ec.edu.espe.view;

import ec.edu.espe.Controller.CustomerController;
import ec.edu.espe.Controller.ProjectController;
import ec.edu.espe.model.Customer;
import ec.edu.espe.model.Project;
import ec.edu.espe.model.ProjectStatus;
import java.awt.SystemColor;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brandon Pazmino
 */
public class ProjectModification extends javax.swing.JFrame {

    private CustomerController customerController = new CustomerController();
    private ProjectController projectController = new ProjectController();
    private Customer customer;
    private MainMenuFrm mainMenu;

    /**
     * Creates new form ModifyProject
     */
    public ProjectModification() {
        initComponents();
        loadProjectIDs();
        jCustomerPanel.setVisible(false);
        Calendar calendar = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = sdf.format(calendar.getTime());
        lblStartDate.setText(formattedDate);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbProjectIDs = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtProjectTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpDescription = new javax.swing.JTextPane();
        rbtnInvoiced = new javax.swing.JRadioButton();
        rbtnNotInvoiced = new javax.swing.JRadioButton();
        jLabel68 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbSector = new javax.swing.JComboBox<>();
        lblStartDate = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        dcrCloseDate = new com.toedter.calendar.JDateChooser();
        jLabel70 = new javax.swing.JLabel();
        txtQuote = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        cmbQuoteStatus = new javax.swing.JComboBox<>();
        jLabel72 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        rbtnPaid = new javax.swing.JRadioButton();
        rbtnNotPaid = new javax.swing.JRadioButton();
        rbtnSelectCustomer = new javax.swing.JRadioButton();
        jCustomerPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblCustomerAdress = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblCustomerId = new javax.swing.JLabel();
        btnCustomerChoose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnProjectSave = new javax.swing.JButton();
        btnDeleteProject = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Seleccione el Proyecto:");

        cmbProjectIDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProjectIDsActionPerformed(evt);
            }
        });

        jLabel3.setText("Nuevo Título:");

        txtProjectTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectTitleActionPerformed(evt);
            }
        });

        jLabel4.setText("Nueva Descipción:");

        jScrollPane1.setViewportView(txtpDescription);

        rbtnInvoiced.setText("Sí");
        rbtnInvoiced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnInvoicedActionPerformed(evt);
            }
        });

        rbtnNotInvoiced.setText("No");
        rbtnNotInvoiced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNotInvoicedActionPerformed(evt);
            }
        });

        jLabel68.setText("Sector:");

        jLabel18.setText("Fecha de creación: ");

        cmbSector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Público", "Privado", " " }));
        cmbSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSectorActionPerformed(evt);
            }
        });

        lblStartDate.setText("StartDate");

        jLabel69.setText("Fecha de cierre: ");

        jLabel70.setText("Presupuesto:");

        txtQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuoteActionPerformed(evt);
            }
        });

        jLabel71.setText("Estado de Presupuesto:");

        cmbQuoteStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enviado", "Rechazado", "Aceptado", " " }));
        cmbQuoteStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQuoteStatusActionPerformed(evt);
            }
        });

        jLabel72.setText("Facturado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jLabel67.setText("Pagado:");

        rbtnPaid.setText("Sí");
        rbtnPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPaidActionPerformed(evt);
            }
        });

        rbtnNotPaid.setText("No");
        rbtnNotPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNotPaidActionPerformed(evt);
            }
        });

        rbtnSelectCustomer.setText("Selecionar Cliente");
        rbtnSelectCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSelectCustomerActionPerformed(evt);
            }
        });

        jCustomerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Dirección:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Nombre:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("RUC:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Código del comprador: ");

        lblRuc.setText(".");

        lblCustomerName.setText(".");

        lblCustomerAdress.setText(".");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Teléfono:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("E-mail");

        lblEmail.setText(".");

        lblPhoneNumber.setText(".");

        lblCustomerId.setText(".");

        btnCustomerChoose.setText("Volver a Escoger");
        btnCustomerChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCustomerPanelLayout = new javax.swing.GroupLayout(jCustomerPanel);
        jCustomerPanel.setLayout(jCustomerPanelLayout);
        jCustomerPanelLayout.setHorizontalGroup(
            jCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCustomerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jCustomerPanelLayout.createSequentialGroup()
                        .addGroup(jCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCustomerChoose)
                .addContainerGap())
        );
        jCustomerPanelLayout.setVerticalGroup(
            jCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblRuc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblCustomerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblCustomerAdress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblPhoneNumber)
                    .addComponent(btnCustomerChoose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 3, 24)); // NOI18N
        jLabel1.setText("Modificar/Eliminar Proyectos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1)
                        .addGap(225, 225, 225)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(txtProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel69)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcrCloseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel70)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnSelectCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbtnPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtnNotPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbtnInvoiced, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtnNotInvoiced, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel71)
                                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbSector, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbQuoteStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cmbProjectIDs, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbProjectIDs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnNotInvoiced)
                                    .addComponent(jLabel72)
                                    .addComponent(rbtnInvoiced)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(rbtnSelectCustomer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel67)
                            .addComponent(rbtnPaid)
                            .addComponent(rbtnNotPaid)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcrCloseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(lblStartDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel70)
                            .addComponent(txtQuote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbQuoteStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel71))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel68)
                            .addComponent(cmbSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(114, 114, 114))
        );

        btnProjectSave.setText("Guardar Datos");
        btnProjectSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjectSaveActionPerformed(evt);
            }
        });

        btnDeleteProject.setText("Borrar Proyecto");
        btnDeleteProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProjectActionPerformed(evt);
            }
        });

        btnGoBack.setText("Regresar al menu principal");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnProjectSave)
                .addGap(267, 267, 267)
                .addComponent(btnDeleteProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGoBack)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProjectSave)
                    .addComponent(btnDeleteProject)
                    .addComponent(btnGoBack))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProjectSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjectSaveActionPerformed
        if (cmbProjectIDs.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un proyecto antes de guardar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String projectId = (String) cmbProjectIDs.getSelectedItem();
        String projectTitle = txtProjectTitle.getText().trim();
        String projectDescription = txtpDescription.getText().trim();
        Date closingDate = dcrCloseDate.getDate();
        double startquote = 0;
        String quoteText = txtQuote.getText().trim();

        if (!quoteText.isEmpty()) {
            startquote = Double.parseDouble(quoteText);
        }

        ProjectStatus quoteStatus = ProjectStatus.fromString(cmbQuoteStatus.getSelectedItem().toString().trim());
        boolean invoiced = rbtnInvoiced.isSelected();
        boolean paid = rbtnPaid.isSelected();
        boolean isPublic = cmbSector.getSelectedItem().toString().equals("Público");

        Project project = new Project.Builder(projectId, projectTitle)
                .setProjectDescription(projectDescription)
                .setCustomer(customer)
                .setStartDate(new Date()) 
                .setClosingDate(closingDate)
                .setStartquote(startquote)
                .setOperationalStatus(ProjectStatus.CREATED) 
                .setQuoteStatus(quoteStatus)
                .setPaid(paid)
                .setInvoiced(invoiced)
                .setPublic(isPublic)
                .build();
        try {
            projectController.updateProject(project);
            JOptionPane.showMessageDialog(this, "Proyecto actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
            loadProjectIDs();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el proyecto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProjectSaveActionPerformed

    private void btnDeleteProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProjectActionPerformed
        if (cmbProjectIDs.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un proyecto para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String projectId = (String) cmbProjectIDs.getSelectedItem();

        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este proyecto?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                projectController.deleteProject(projectId);
                JOptionPane.showMessageDialog(this, "Proyecto eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                loadProjectIDs();
                clearFields();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar el proyecto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteProjectActionPerformed

    private void cmbQuoteStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQuoteStatusActionPerformed

    }//GEN-LAST:event_cmbQuoteStatusActionPerformed

    private void txtQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuoteActionPerformed

    private void cmbSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSectorActionPerformed

    private void rbtnNotInvoicedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNotInvoicedActionPerformed
        if (rbtnNotInvoiced.isSelected()) {
            rbtnNotInvoiced.setSelected(true);
            rbtnInvoiced.setSelected(false);
        }
    }//GEN-LAST:event_rbtnNotInvoicedActionPerformed

    private void rbtnInvoicedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnInvoicedActionPerformed
        if (rbtnInvoiced.isSelected()) {
            rbtnInvoiced.setSelected(true);
            rbtnNotInvoiced.setSelected(false);
        }
    }//GEN-LAST:event_rbtnInvoicedActionPerformed

    private void txtProjectTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectTitleActionPerformed

    }//GEN-LAST:event_txtProjectTitleActionPerformed

    private void cmbProjectIDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProjectIDsActionPerformed

    }//GEN-LAST:event_cmbProjectIDsActionPerformed

    private void rbtnPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPaidActionPerformed
        if (rbtnPaid.isSelected()) {
            rbtnPaid.setSelected(true);
            rbtnNotPaid.setSelected(false);
        }
    }//GEN-LAST:event_rbtnPaidActionPerformed

    private void rbtnNotPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNotPaidActionPerformed
        if (rbtnNotPaid.isSelected()) {
            rbtnNotPaid.setSelected(true);
            rbtnPaid.setSelected(false);
        }
    }//GEN-LAST:event_rbtnNotPaidActionPerformed

    private void rbtnSelectCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSelectCustomerActionPerformed
        if (rbtnSelectCustomer.isSelected()) {
            LoadCustomerFrm customerFrame = new LoadCustomerFrm(this);
            customerFrame.setVisible(true);
        } else {
            jCustomerPanel.setVisible(false);
        }
    }//GEN-LAST:event_rbtnSelectCustomerActionPerformed

    private void btnCustomerChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerChooseActionPerformed
        if (rbtnSelectCustomer.isSelected()) {
            LoadCustomerFrm loadCustomerFrm = new LoadCustomerFrm(this);
            loadCustomerFrm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una opción antes de continuar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCustomerChooseActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        this.dispose();
        if (mainMenu != null) {
            mainMenu.setVisible(true);
        }
    }//GEN-LAST:event_btnGoBackActionPerformed

    public void changelblName(Customer customer) {
        if (customer != null) {
            lblCustomerName.setText(customer.getName());
            lblCustomerId.setText(customer.getCustomerId());
            lblEmail.setText(customer.getEmail());
            lblPhoneNumber.setText(customer.getPhoneNumber());
            lblRuc.setText(customer.getRuc());
            lblCustomerAdress.setText(customer.getAddress());
        } else {
            lblCustomerName.setText("No customer selected");
            lblCustomerId.setText("");
            lblEmail.setText("");
            lblPhoneNumber.setText("");
            lblRuc.setText("");
            lblCustomerAdress.setText("");
        }
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
        if (customer != null) {
            lblCustomerName.setText(customer.getName());
            lblCustomerId.setText(customer.getCustomerId());
            lblEmail.setText(customer.getEmail());
            lblPhoneNumber.setText(customer.getPhoneNumber());
            lblRuc.setText(customer.getRuc());
            lblCustomerAdress.setText(customer.getAddress());
            jCustomerPanel.setVisible(true); // Muestra el panel si hay un cliente
        }
    }

    private void loadProjectIDs() {
        List<String> projectIds = projectController.findAllProjectIds();

        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

        for (String id : projectIds) {
            comboBoxModel.addElement(id);
        }

        cmbProjectIDs.setModel(comboBoxModel);
    }

    private void clearFields() {
        txtProjectTitle.setText("");
        txtpDescription.setText("");
        txtQuote.setText("");
        cmbQuoteStatus.setSelectedIndex(0);
        rbtnInvoiced.setSelected(false);
        rbtnPaid.setSelected(false);
        cmbSector.setSelectedIndex(0);
        dcrCloseDate.setDate(null);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectModification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectModification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerChoose;
    private javax.swing.JButton btnDeleteProject;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnProjectSave;
    private javax.swing.JComboBox<String> cmbProjectIDs;
    private javax.swing.JComboBox<String> cmbQuoteStatus;
    private javax.swing.JComboBox<String> cmbSector;
    private com.toedter.calendar.JDateChooser dcrCloseDate;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jCustomerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerAdress;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JRadioButton rbtnInvoiced;
    private javax.swing.JRadioButton rbtnNotInvoiced;
    private javax.swing.JRadioButton rbtnNotPaid;
    private javax.swing.JRadioButton rbtnPaid;
    private javax.swing.JRadioButton rbtnSelectCustomer;
    private javax.swing.JTextField txtProjectTitle;
    private javax.swing.JTextField txtQuote;
    private javax.swing.JTextPane txtpDescription;
    // End of variables declaration//GEN-END:variables
}
