package ec.edu.espe.view;

import ec.edu.espe.Controller.QuoteChangeLogController;
import ec.edu.espe.Controller.ProjectController;
import ec.edu.espe.Controller.QuoteStatusChangeLogController;
import com.mongodb.client.MongoDatabase;
import ec.edu.espe.model.Project;
import ec.edu.espe.model.QuoteChangeLog;
import ec.edu.espe.model.QuoteStatusChangeLog;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon Pazmino
 */
public class QuoteStateUpdaterFrm extends javax.swing.JFrame {

    private QuoteChangeLogController quoteChangeLogController = new QuoteChangeLogController();
    private QuoteStatusChangeLogController quoteStatusChangeLogController = new QuoteStatusChangeLogController();
    private ProjectController projectController = new ProjectController();
    

    /**
     * Creates new form QuoteStateUpdater
     */
    public QuoteStateUpdaterFrm() {
        initComponents();
        loadProjectIDs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSaveQuoteChange = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbSelectUpdates = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbProjectIDs = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNewQuote = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 3, 24)); // NOI18N
        jLabel1.setText("Cambios de Presupuesto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnSaveQuoteChange.setText("Guardar Cambios");
        btnSaveQuoteChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveQuoteChangeActionPerformed(evt);
            }
        });

        btnGoBack.setText("Regresar al menu principal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnSaveQuoteChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGoBack)
                .addGap(123, 123, 123))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveQuoteChange)
                    .addComponent(btnGoBack))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setText("Seleccione que cambio desea realizar:");

        cmbSelectUpdates.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actualizar Presupuesto", "Actualizar Estatus" }));
        cmbSelectUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectUpdatesActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione el ID del Proyecto:");

        cmbProjectIDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProjectIDsActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese el Nuevo Presupuesto:");

        txtNewQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewQuoteActionPerformed(evt);
            }
        });

        jLabel5.setText("Seleccione el Nuevo Estado del Projecto:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Creado", "En Progreso", "Pausado ", "Cerrado", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSelectUpdates, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNewQuote)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbProjectIDs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSelectUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbProjectIDs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewQuote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSelectUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectUpdatesActionPerformed
        String selectedAction = (String) cmbSelectUpdates.getSelectedItem();

        // Habilitar o deshabilitar campos según la acción seleccionada
        if ("Actualizar Presupuesto".equals(selectedAction)) {
            txtNewQuote.setEnabled(true); // Habilitar el campo de nuevo presupuesto
            jComboBox1.setEnabled(false); // Deshabilitar el JComboBox para el estatus
        } else if ("Actualizar Estatus".equals(selectedAction)) {
            txtNewQuote.setEnabled(false); // Deshabilitar el campo de nuevo presupuesto
            jComboBox1.setEnabled(true); // Habilitar el JComboBox para el estatus
        } else {
            // Si no se selecciona ninguna acción válida, deshabilitar ambos
            txtNewQuote.setEnabled(false);
            jComboBox1.setEnabled(false);
        }
    }//GEN-LAST:event_cmbSelectUpdatesActionPerformed

    private void btnSaveQuoteChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveQuoteChangeActionPerformed
        String projectId = (String) cmbProjectIDs.getSelectedItem();
        String selectedAction = (String) cmbSelectUpdates.getSelectedItem();

        if (projectId.equals("Selecciona un proyecto")) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un proyecto.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (selectedAction.equals("Selecciona una acción")) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una acción válida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String projectTitle = "Título del Proyecto";
            Date changeDate = new Date();

            if ("Actualizar Presupuesto".equals(selectedAction)) {
                String newBudgetStr = txtNewQuote.getText().trim();
                if (newBudgetStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Por favor, ingresa un nuevo presupuesto.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                double oldQuote = 0.0;
                double newQuote = Double.parseDouble(newBudgetStr);
                QuoteChangeLog changeLog = new QuoteChangeLog(projectId, projectTitle, oldQuote, newQuote, changeDate);
                quoteChangeLogController.saveQuoteChangeLog(changeLog);

                JOptionPane.showMessageDialog(this, "Presupuesto actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else if ("Actualizar Estatus".equals(selectedAction)) {
                String newStatus = (String) jComboBox1.getSelectedItem();
                if (newStatus == null || newStatus.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Por favor, selecciona un nuevo estatus.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                String oldQuoteStatus = "Estado Anterior";
                QuoteStatusChangeLog statusChangeLog = new QuoteStatusChangeLog(projectId, projectTitle, oldQuoteStatus, newStatus, changeDate);
                quoteStatusChangeLogController.saveQuoteStatusChangeLog(statusChangeLog);

                JOptionPane.showMessageDialog(this, "Estatus actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
            clearFields();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el cambio: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveQuoteChangeActionPerformed

    private void cmbProjectIDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProjectIDsActionPerformed
        
    }//GEN-LAST:event_cmbProjectIDsActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtNewQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewQuoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewQuoteActionPerformed

private void loadProjectIDs() {
    // Obtener los IDs desde MongoDB
    List<String> projectIds = projectController.findAllProjectIds();
    
    // Crear el modelo para el JComboBox
    DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
    
    // Agregar los IDs al modelo
    for (String id : projectIds) {
        comboBoxModel.addElement(id);
    }
    
    // Establecer el modelo al JComboBox
    cmbProjectIDs.setModel(comboBoxModel);
}

    private void clearFields() {
        cmbProjectIDs.setSelectedIndex(0);
        cmbSelectUpdates.setSelectedIndex(0);
        txtNewQuote.setText("");
        jComboBox1.setSelectedIndex(-1);
        txtNewQuote.setEnabled(false);
        jComboBox1.setEnabled(false);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuoteStateUpdaterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuoteStateUpdaterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuoteStateUpdaterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuoteStateUpdaterFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuoteStateUpdaterFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnSaveQuoteChange;
    private javax.swing.JComboBox<String> cmbProjectIDs;
    private javax.swing.JComboBox<String> cmbSelectUpdates;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtNewQuote;
    // End of variables declaration//GEN-END:variables
}
